hand_annotations_file: arc_memo/data/abstract_anno/gui/example_annotations.yaml
example_concepts: arc_memo/data/abstract_anno/gui/example_concepts.yaml
example_trajectories: arc_memo/data/abstract_anno/gui/example_trajectories_annotations.json
trajectories: arc_memo/data/webvoyager_memory/extracted_trajectories_shopping.json
task_descriptions: arc_memo/data/webvoyager_memory/extracted_task_descriptions_shopping.json
limit_tasks: null
model:
  server_url: http://localhost:8000/v1
  name: Qwen/Qwen2.5-VL-7B-Instruct
  api_key: EMPTY
output_dir: arc_memo/output
dry_run: false
